version: '3.8'

services:
  user-service:
    build:
      context: .  # Changed to root project directory
      dockerfile: Dockerfile  # Explicitly specify the root Dockerfile
    image: eventlinkr-user-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=eventlinkr
      - DATABASE_USERNAME=eventlinkr
      - DATABASE_PASSWORD=eventlinkr
    depends_on:
      - postgres
    networks:
      - eventlinkr-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=eventlinkr
      - POSTGRES_USER=eventlinkr
      - POSTGRES_PASSWORD=eventlinkr
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - eventlinkr-network

volumes:
  postgres-data:

networks:
  eventlinkr-network:
    driver: bridge