spring:
  application:
    name: architecture-service

  profiles:
    active: local

  # H2 Database Configuration
  datasource:
    url: jdbc:h2:mem:wisetect
    driverClassName: org.h2.Driver
    username: sa
    password:

  r2dbc:
    url: r2dbc:h2:mem:///wisetect?options=DB_CLOSE_DELAY=-1
    username: sa
    password:

  h2:
    console:
      enabled: true

  flyway:
    url: jdbc:h2:mem:wisetect
    user: sa
    password:
    locations:
      - classpath:db/migration/{vendor}
    baseline-on-migrate: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://your-keycloak-server/realms/wisetect
  server:
  port: 8080

# Actuator Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true

# Logging Configuration
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.r2dbc: DEBUG
