name: WiseTect CI/CD

on:
  push:
    branches: [main, infra, dev]
    paths:
      - "architecture-service/**"
      - ".github/workflows/architecture-service-ci.yml"
  pull_request:
    branches: [main, infra, dev]
    paths:
      - "architecture-service/**"
      - ".github/workflows/architecture-service-ci.yml"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "maven"

      - name: Install Root POM
        run: mvn clean install -DskipTests

      - name: Build and Test Architecture Service with Coverage
        run: |
          cd architecture-service
          mvn clean verify jacoco:report

      - name: Run Mutation Tests
        run: |
          cd architecture-service
          mvn org.pitest:pitest-maven:mutationCoverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Ilagouilly/WiseTect

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd architecture-service
          mvn sonar:sonar -Dsonar.projectKey=Ilagouilly_WiseTect \
                          -Dsonar.organization=ilagouilly \
                          -Dsonar.host.url=https://sonarcloud.io \
                          -Dsonar.login=$SONAR_TOKEN
